[options]
limit_time_real = 3600
limit_time_cpu = 1800
limit_memory_hard = 0
limit_memory_soft = 0
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons 
db_host = db 
db_port = 5432 
db_user = odoo 
db_password = odoo
db_name = odoo_db
admin_passwd = $pbkdf2-sha512$600000$zvkf43yPMQaA0BoDgDDGWA$1/wrSu57A3cTXkZnv1Izu1X1POpBonI4viKJzHJ6H4gITgwbFYKhOhuHI2UTEraZNNckdc/iG5ayGmhpH2YU2A 