from . import x3_article_cache
from . import x3_sync_history
from . import x3_sync_configuration
from . import x3_consultation_history
from . import res_users
from . import x3_tariff_littoral
from . import x3_tariff_bamenda
from . import x3_tariff_centre
from . import x3_tariff_ouest
from . import x3_tariff_kribi
from . import x3_tariff_bertoua
from . import x3_tariff_ngaoundere
